- hosts: all
  tasks:
    - name: export GUID
      shell: bash -lc 'export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc'

- hosts: nfs
  tasks:
    - name: exportfs
      shell: bash -lc 'exportfs'

- hosts: 127.0.0.1
  tasks:
    - name: install atomic-openshift-utils
      yum:
        state: present
        name: atomic-openshift-utils
    - name: install atomic-openshift-clients
      yum:
        state: present
        name: atomic-openshift-clients
