- host: all
  tasks:
    - name: export GUID
      shell: |
        'export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc'

- host: nfs
  tasks:
    - name: exportfs
      shell: |
        'exportfs'

- host: 127.0.0.1
  tasks:
    - name: install atomic-openshift-utils and atomic-openshift-clients
      yum:
        status: present
        name: "{{ item }}"
      with_items:
        - atomic-openshift-utils
        - atomic-openshift-clients

- hosts: masters
  become: true
  tasks:
    - name: install httpd-tools
      yum:
        state: present
        name: httpd-tools

    - name: create user webadmin
      shell: |
        htpasswd -b /etc/origin/master/htpasswd "{{ item }}" r3dh4t1!
      with_items:
        - webadmin

# if you need web console, uncomment this part
#- hosts: 127.0.0.1
#  tasks:
#    - name: add cluster role to 'webadmin' clusster-admin
#      shell: |
#        oc adm policy add-cluster-role-to-user cluster-admin webadmin

