- name: Create dir for pv files
  file:
    dest: "/root/pvs"
    state: directory

- name: Create 5Gi PV files
  template:
    src: pv_5Gi.yml.j2
    dest: "/root/pvs/pv{{ item }}"
  with_sequence: start=1 end=25 stride=1

- name: Create 10Gi PV files
  template:
    src: pv_10Gi.yml.j2
    dest: "/root/pvs/pv{{ item }}"
  with_sequence: start=26 end=50 stride=1

- name: oc create pv
  shell: |
    oc create -f /root/pvs/pv{{ item }}
  with_sequence: start=1 end=50 stride=1


#- name: create pv
#  oc:
#    state: present
#    token: 
#    inline:
#      apiVersion: v1
#      kind: PersistentVolume
#      metadata:
#        name: "{{item}}"
#      spec:
#        capacity:
#          storage: 5Gi
#        accessModes:
#        - ReadWriteOnce
#        nfs:
#          path: "/srv/nfs/user-vols/{{item}}"
#          server: "support1.{{guid}}.internal"
#        persistentVolumeReclaimPolicy: Recycle
#  with_sequence: start=1 end=2 stride=1
